on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'terraform/**'
      - '.github/workflows/**'
      - 'main/**'
  workflow_dispatch:

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    outputs:
      droplet_ip: ${{ steps.set_outputs.outputs.droplet_ip }}
      private_key: ${{ steps.set_outputs.outputs.private_key }}
    
    permissions:
      contents: read
      actions: write
    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_s3_access: ${{ secrets.S3_ACCESS }}
      TF_VAR_s3_secret: ${{ secrets.S3_SECRET }}
      TF_VAR_cloudflare_api: ${{ secrets.CLOUDFLARE_API }}
      TF_VAR_cloudflare_id: ${{ secrets.CLOUDFLARE_ID }}

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup terraform
          uses: hashicorp/setup-terraform@v3
        
        - name: Deploying Infrastructure

          run: terraform init -reconfigure
        - run: terraform plan -input=false
        - run: terraform apply -auto-approve -input=false

        - name: Update secrets
          id: set_outputs
          #Taking raw data after vm starts and creating new secrets
          run: |
            IP=$(terraform output -raw droplet_ip)
            KEY=$(terraform output -raw private_key)

            echo "droplet_ip=$IP" >> $GITHUB_OUTPUT
            echo "private_key<<EOF" >> $GITHUB_OUTPUT
            echo "$KEY" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT


            gh secret set DROPLET_IP --body "$IP"
            echo "$KEY" | gh secret set SSH_PRIVATE_KEY
          env:
            GH_TOKEN: ${{ secrets.GH_PAT }}
     
  container-deployment:
    needs: 'server-deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main
    steps:
      - uses: actions/checkout@v4

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.server-deploy.outputs.droplet_ip }}
          username: root
          key: ${{needs.server-deploy.outputs.private_key }}
          script: |
            git clone https://github.com/Lugen-dl/ISW.git
            cd ISW/main
            
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTRGES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "CLOUDFARE_DOMAIN"=${{ secrets.DOCKER_TUNNEL }} >> .env
            
            docker compose up -d --build
          

          


#  registry-login:
#    needs: 'server-deploy'
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DO_TOKEN }}
#      
#      - name: Log in DO registry
#        run: |
#          snap connect doctl:dot-docker
#          doctl registry login
#
#
#      - name: Building Compose containers
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets }}
#          username: root
#          key: ${{ secrets }}
#          source: "ISW/main/docker-compose.yml"
#          target: "/root/app/"
