name: ISW destroy

on:
  pull_request:
    branches:
        - 'main'
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_s3_access: ${{ secrets.S3_ACCESS }}
      TF_VAR_s3_secret: ${{ secrets.S3_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
